version: "2"
services:
  city-info:
    build:
      context: .
      dockerfile: Dockerfile
    image: city-info-image
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=cityinfo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
