openapi: 3.0.1
info:
  title: cities-info-application
  description: REST-API на чтение и изменение справочника регионов.
  contact:
    name: Анастасия Фирман
    email: fakemail@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/city
tags:
  - name: CityController
    description: Контроллер для работы со справочником регионов
paths:
  /city:
    get:
      summary: Получение списка всех регионов
      description: Получение списка всех регионов
      tags:
        - CityController
      operationId: findAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '500':
          description: Internal server error
    post:
      tags:
        - CityController
      operationId: save
      summary: Добавление нового региона в справочник
      description: Добавление нового региона в справочник
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '500':
          description: Internal server error



  /city/{regionCode}:
    get:
      summary: Получение города по коду региона
      description: Получение города по коду региона
      tags:
        - CityController
      operationId: findByRegionCode
      parameters:
        - name: regionCode
          in: path
          required: true
          description: код региона
          schema:
            type: string
            example: 199
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '500':
          description: Internal server error

    put:
      tags:
        - CityController
      operationId: update
      parameters:
        - name: regionCode
          in: path
          required: true
          description: код региона
          schema:
            type: string
            example: 199
      summary: Обновление региона
      description: Обновление региона
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '500':
          description: Internal server error

    delete:
      summary: удаление региона по коду
      description: удаление региона по коду
      tags:
        - CityController
      operationId: deleteByRegionCode
      parameters:
        - name: regionCode
          in: path
          required: true
          description: код региона
          schema:
            type: string
            example: 199
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '500':
          description: Internal server error
components:
  schemas:
    City:
      type: object
      properties:
        regionCode:
          type: string
          example: 199
          description: Код региона
        name:
          type: string
          example: Москва
          description: Название города
      required: [name, regionCode]
    CitiesListResponse:
      type: array
      items:
        $ref: '#/components/schemas/City'